steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dtu-mlops-410811/streamlitapp:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtu-mlops-410811/streamlitapp:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'streamlitappexmp'
  - '--image'
  - 'gcr.io/dtu-mlops-410811/streamlit_app:latest'
  - '--region'
  - 'europe-west3'
